### ISSUE TITLE
wiselike json importer

### ISSUE THREAD

**Issue by youchenlee** [g0v/wiselike.tw#2]
import https://raw.githubusercontent.com/audreyt/archive.tw/gh-pages/wiselike-2017-01-30-backup.json to Discourse (talk.vTaiwan.tw)

**Comment by audreyt** [comment]
We're thinking to import it to https://ask.PDIS.tw instead, as to not flood the vTaiwan community.

@targee fixed the parser and I've regenerated the `.json` above.
